### ISSUE TITLE
Installing for Newbies

### ISSUE THREAD

**Issue by cauenapier** [jacobwilliams/Fortran-Astrodynamics-Toolkit#8]
Hello Jacob,

I have started working with Fortran for a while now, but I have been using a REALLY old compiler (MS PowerStation) and some codes from my professor.

Could you please help me start working with your code?
I was not able to compile it. Could you please help me with the step-by-step?

**Comment by jacobwilliams** [comment]
I'm afraid it isn't going to compile with Fortran PowerStation (which as you say is a really old compiler, with no support for Fortran 2003 or 2008). You need a recent version of a modern Fortran compiler. Either gfortran (free) and Intel Fortran (not free) should both work. 

On the Mac, I compile using the `build.sh` script with gfortran. It might also work on Windows, but I haven't tried it (note that it requires [FoBiS.py](https://github.com/szaghi/FoBiS) to be installed.

**Comment by cauenapier** [comment]
Thanks Jacob!
I started working with gfortran recently. I will try installing FoBiS and see if it works.
If not, I will try on Linux

**Comment by szaghi** [comment]
@cauenapier If you have problem to install FoBiS let me know. @jacobwilliams are you using FoBiS on Mac? Probably you have already told me, but my memory is bugged... Have I add some instructions to install FoBiS on Mac or it is installed smooth as in GNU Linux?

**Comment by jacobwilliams** [comment]
@szaghi Yes, I've only ever used FoBiS on a Mac. I install with `pip` and it works great!

**Comment by szaghi** [comment]
@jacobwilliams Thank you, I'll an *obscure* sentence that the PiPy install works also on Mac :smile:

**Comment by cauenapier** [comment]
Hello Guys,

I have installed all the requirements on ubuntu.
But I have never used fortran libraries before. I have just used one file code.

Do you have any link explaining how to work with it? 
Or how to run the examples?

Thank you very much for the attention and sorry for bothering.

**Comment by szaghi** [comment]
@cauenapier 

I cannot help very much for this great project of @jacobwilliams (I never used it *as whole project* rather I studied the sources), but inspecting the build script, if you have installed FoBiS, you can simply do (in the project root directory):

```shell
./build.sh
``` 

Then, if all goes right, you will have 2 new directories (at least): `tests` and `lib`. In the first there are the executables of the provided tests while in the latter there is the compiled library that you can use in your own projects.

If you need help to use the library in your own projects I can try to help further. Anyway, wait the Jacobs helps because he can give us the right instructions.

My best regards.

**Comment by jacobwilliams** [comment]
Note that the latest readme has more information on how to build it with FoBiS.
